### ISSUE TITLE
Chatbot command for halpy to remind us of deadlines

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-hubot-halpy#35]
Beyond the built-in slack reminder functionality, there are some specific cases where we want...
ongoing and increasingly persistent reminders:

From slack convo: https://edgi.slack.com/archives/C57QL8M1T/p1536937119000100

> - send out a message say a week before the end of the month, asking for a the reports
> - tag everyone who needs to write one
> - somehow allow them to signal that they've completed the report, either with a comment or a reaction emoji
> - send out subsequent, increasingly urgent, messages that only tag the folks who haven't responded.

Research turned up:
- https://github.com/appcues/cuebot/blob/master/scripts/poll.coffee
- https://finalem.com/must-read
- https://github.com/ndaversa/hubot-reminder-bot/blob/master/src/reminder.coffee
- https://www.npmjs.com/package/hubot-reminder-bot

**Comment by dcwalk** [comment]
ping @titaniumbones so you know I spawned an issue on this

**Comment by titaniumbones** [comment]
This turns out to be a little harder than it might look at first, I think.  There are two or three parts:

- schedule a repeating nagging request
- ideally, send that request from the original requester, **not** from halpy
- make the request stand out, so that people actually pay attention to
- make the request easy to interact with, e.g. with emoji or with custom buttons
- identify a way to allow people to remove themselves from the distribution list (for the nagging)
- would be nice to be able to modify the request post-facto, too.

So, some pieces:
- scheduler that sends the messages out at end of month. This should probably be triggered manually by a request to `halpy` that includes the @-mentions of all WG reps
- consider using a JSON payload to construct "attachments" as descrbed in the [Slack API docs](https://api.slack.com/docs/message-attachments). 
- Get halpy to listen to the emoji reactions (or buttons) attached to each of these messages, and respond to those actions by removing form the a-mention list those people who have already responded (also possibly adding new people??)
- convince people to use this method!!

**Comment by titaniumbones** [comment]
mivng these htoughts out of my head into the issue:
- report reminders should be scheduled automaticlaly -- regardless of whether Stephanie sends them out, they hsould go out
- stephanie (or others) should be able to set the initial recipients for current and future report reminders with, e.g. `@halpy report recipients @user1 @user2 @user3`
- there should be a simple mechanism (ideally an emoji reaction) for tagged users to remove themselves from future reminders for hte ucrrent month
- then reminders should go out until there are no outstanding reports.

The list of recipients needs to be stored in persistent storage, using the robot.brain.  

Easiest way to do all this is likely to `require` one of hte hubot reminder/scheduler scripts, then add to theri persistent store using our own methods.  But it's possible none of htose really fit our purposes right now.
